### ISSUE TITLE
NullPointerException when running incremental

### ISSUE THREAD

**Issue by carmenvandeloo** [nkons/r2rml-parser#30]
Hi,

When running with default.incremental set to true in the r2rml.properties file, a NullPointerException is thrown:

```
Transforming the data... Run with -h for help on options.
Exception in thread "main" java.lang.NullPointerException
        at gr.seab.r2rml.beans.UtilImpl.md5(UtilImpl.java:398)
        at gr.seab.r2rml.beans.Generator.createTriples(Generator.java:792)
        at gr.seab.r2rml.beans.Main.main(Main.java:93)
```

I had a look at the code and I believe line 398 should simply be moved inside the if clause directly following it:

Current code:
```
s += predicateObjectMap.getObjectTemplate().getLanguage();
if (predicateObjectMap.getObjectTemplate() != null) {
	s += predicateObjectMap.getObjectTemplate().getText();
} else {
	s += predicateObjectMap.getObjectColumn();
}
```

Proposed code:
```
if (predicateObjectMap.getObjectTemplate() != null) {
	s += predicateObjectMap.getObjectTemplate().getLanguage();
	s += predicateObjectMap.getObjectTemplate().getText();
} else {
	s += predicateObjectMap.getObjectColumn();
}
```

Could you please confirm this?

**Comment by nkons** [comment]
HI,

Thanks for spotting this. A check for null would prevent this from happening, e.g.

    s += predicateObjectMap.getObjectTemplate() != null? predicateObjectMap.getObjectTemplate().getLanguage() : "null";
